baseURL = 'https://academics.mohibulalam.xyz'
languageCode = 'en-us'
title = 'Distributed Systems Lab'
theme = "hugo-book"
uglyURLs = false
googleAnalytics='G-T1GNGFG1C4'

disableAdsense = false

[params]
  author = "Mohibul Alam"
  description = "Sharing dev notes and academic thoughts"
  keywords = ["Distributed Systems", "Microservices", "Docker", "Nginx", "System Design"]
  siteName = "Distributed Systems Lab"
  bookCollapseSection = true
  