baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Distributed Systems Lab'
theme = "hugo-book"
uglyURLs = false

disableAdsense = false

[params]
  author = "Mohibul Alam"
  description = "Sharing dev notes and academic thoughts"
  keywords = ["Distributed Systems", "Microservices", "Docker", "Nginx", "System Design"]
  siteName = "Distributed Systems Lab"
  