name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActionsSession

      - name: 📦 Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: 🏗 Build Hugo site
        run: hugo --minify

      - name: Deploy to Dev
        run: |
          aws s3 sync dist/ s3://${{ secrets.AWS_BUCKET_NAME }} --region ${{ secrets.AWS_REGION }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*" --region ${{ secrets.AWS_REGION }}
